// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/ONSDigital/blaise-uac-service/blaiserestapi"
	mock "github.com/stretchr/testify/mock"
)

// NewBlaiseRESTAPIInterface creates a new instance of BlaiseRESTAPIInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBlaiseRESTAPIInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *BlaiseRESTAPIInterface {
	mock := &BlaiseRESTAPIInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// BlaiseRESTAPIInterface is an autogenerated mock type for the BlaiseRESTAPIInterface type
type BlaiseRESTAPIInterface struct {
	mock.Mock
}

type BlaiseRESTAPIInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *BlaiseRESTAPIInterface) EXPECT() *BlaiseRESTAPIInterface_Expecter {
	return &BlaiseRESTAPIInterface_Expecter{mock: &_m.Mock}
}

// GetCaseIDs provides a mock function for the type BlaiseRESTAPIInterface
func (_mock *BlaiseRESTAPIInterface) GetCaseIDs(s string) ([]string, error) {
	ret := _mock.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for GetCaseIDs")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]string, error)); ok {
		return returnFunc(s)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []string); ok {
		r0 = returnFunc(s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// BlaiseRESTAPIInterface_GetCaseIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCaseIDs'
type BlaiseRESTAPIInterface_GetCaseIDs_Call struct {
	*mock.Call
}

// GetCaseIDs is a helper method to define mock.On call
//   - s string
func (_e *BlaiseRESTAPIInterface_Expecter) GetCaseIDs(s any) *BlaiseRESTAPIInterface_GetCaseIDs_Call {
	return &BlaiseRESTAPIInterface_GetCaseIDs_Call{Call: _e.mock.On("GetCaseIDs", s)}
}

func (_c *BlaiseRESTAPIInterface_GetCaseIDs_Call) Run(run func(s string)) *BlaiseRESTAPIInterface_GetCaseIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *BlaiseRESTAPIInterface_GetCaseIDs_Call) Return(strings []string, err error) *BlaiseRESTAPIInterface_GetCaseIDs_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *BlaiseRESTAPIInterface_GetCaseIDs_Call) RunAndReturn(run func(s string) ([]string, error)) *BlaiseRESTAPIInterface_GetCaseIDs_Call {
	_c.Call.Return(run)
	return _c
}

// GetInstrumentModes provides a mock function for the type BlaiseRESTAPIInterface
func (_mock *BlaiseRESTAPIInterface) GetInstrumentModes(s string) (blaiserestapi.InstrumentModes, error) {
	ret := _mock.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for GetInstrumentModes")
	}

	var r0 blaiserestapi.InstrumentModes
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (blaiserestapi.InstrumentModes, error)); ok {
		return returnFunc(s)
	}
	if returnFunc, ok := ret.Get(0).(func(string) blaiserestapi.InstrumentModes); ok {
		r0 = returnFunc(s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(blaiserestapi.InstrumentModes)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// BlaiseRESTAPIInterface_GetInstrumentModes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInstrumentModes'
type BlaiseRESTAPIInterface_GetInstrumentModes_Call struct {
	*mock.Call
}

// GetInstrumentModes is a helper method to define mock.On call
//   - s string
func (_e *BlaiseRESTAPIInterface_Expecter) GetInstrumentModes(s any) *BlaiseRESTAPIInterface_GetInstrumentModes_Call {
	return &BlaiseRESTAPIInterface_GetInstrumentModes_Call{Call: _e.mock.On("GetInstrumentModes", s)}
}

func (_c *BlaiseRESTAPIInterface_GetInstrumentModes_Call) Run(run func(s string)) *BlaiseRESTAPIInterface_GetInstrumentModes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *BlaiseRESTAPIInterface_GetInstrumentModes_Call) Return(instrumentModes blaiserestapi.InstrumentModes, err error) *BlaiseRESTAPIInterface_GetInstrumentModes_Call {
	_c.Call.Return(instrumentModes, err)
	return _c
}

func (_c *BlaiseRESTAPIInterface_GetInstrumentModes_Call) RunAndReturn(run func(s string) (blaiserestapi.InstrumentModes, error)) *BlaiseRESTAPIInterface_GetInstrumentModes_Call {
	_c.Call.Return(run)
	return _c
}
