// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"cloud.google.com/go/datastore"
	mock "github.com/stretchr/testify/mock"
)

// NewDatastoreInterface creates a new instance of DatastoreInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDatastoreInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *DatastoreInterface {
	mock := &DatastoreInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// DatastoreInterface is an autogenerated mock type for the DatastoreInterface type
type DatastoreInterface struct {
	mock.Mock
}

type DatastoreInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *DatastoreInterface) EXPECT() *DatastoreInterface_Expecter {
	return &DatastoreInterface_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type DatastoreInterface
func (_mock *DatastoreInterface) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// DatastoreInterface_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type DatastoreInterface_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *DatastoreInterface_Expecter) Close() *DatastoreInterface_Close_Call {
	return &DatastoreInterface_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *DatastoreInterface_Close_Call) Run(run func()) *DatastoreInterface_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *DatastoreInterface_Close_Call) Return(err error) *DatastoreInterface_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *DatastoreInterface_Close_Call) RunAndReturn(run func() error) *DatastoreInterface_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Count provides a mock function for the type DatastoreInterface
func (_mock *DatastoreInterface) Count(context1 context.Context, query *datastore.Query) (int, error) {
	ret := _mock.Called(context1, query)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *datastore.Query) (int, error)); ok {
		return returnFunc(context1, query)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *datastore.Query) int); ok {
		r0 = returnFunc(context1, query)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *datastore.Query) error); ok {
		r1 = returnFunc(context1, query)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DatastoreInterface_Count_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Count'
type DatastoreInterface_Count_Call struct {
	*mock.Call
}

// Count is a helper method to define mock.On call
//   - context1 context.Context
//   - query *datastore.Query
func (_e *DatastoreInterface_Expecter) Count(context1 any, query any) *DatastoreInterface_Count_Call {
	return &DatastoreInterface_Count_Call{Call: _e.mock.On("Count", context1, query)}
}

func (_c *DatastoreInterface_Count_Call) Run(run func(context1 context.Context, query *datastore.Query)) *DatastoreInterface_Count_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *datastore.Query
		if args[1] != nil {
			arg1 = args[1].(*datastore.Query)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DatastoreInterface_Count_Call) Return(n int, err error) *DatastoreInterface_Count_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *DatastoreInterface_Count_Call) RunAndReturn(run func(context1 context.Context, query *datastore.Query) (int, error)) *DatastoreInterface_Count_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteMulti provides a mock function for the type DatastoreInterface
func (_mock *DatastoreInterface) DeleteMulti(context1 context.Context, keys []*datastore.Key) error {
	ret := _mock.Called(context1, keys)

	if len(ret) == 0 {
		panic("no return value specified for DeleteMulti")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []*datastore.Key) error); ok {
		r0 = returnFunc(context1, keys)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// DatastoreInterface_DeleteMulti_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteMulti'
type DatastoreInterface_DeleteMulti_Call struct {
	*mock.Call
}

// DeleteMulti is a helper method to define mock.On call
//   - context1 context.Context
//   - keys []*datastore.Key
func (_e *DatastoreInterface_Expecter) DeleteMulti(context1 any, keys any) *DatastoreInterface_DeleteMulti_Call {
	return &DatastoreInterface_DeleteMulti_Call{Call: _e.mock.On("DeleteMulti", context1, keys)}
}

func (_c *DatastoreInterface_DeleteMulti_Call) Run(run func(context1 context.Context, keys []*datastore.Key)) *DatastoreInterface_DeleteMulti_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []*datastore.Key
		if args[1] != nil {
			arg1 = args[1].([]*datastore.Key)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DatastoreInterface_DeleteMulti_Call) Return(err error) *DatastoreInterface_DeleteMulti_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *DatastoreInterface_DeleteMulti_Call) RunAndReturn(run func(context1 context.Context, keys []*datastore.Key) error) *DatastoreInterface_DeleteMulti_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type DatastoreInterface
func (_mock *DatastoreInterface) Get(context1 context.Context, key *datastore.Key, ifaceVal interface{}) error {
	ret := _mock.Called(context1, key, ifaceVal)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *datastore.Key, interface{}) error); ok {
		r0 = returnFunc(context1, key, ifaceVal)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// DatastoreInterface_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type DatastoreInterface_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - context1 context.Context
//   - key *datastore.Key
//   - ifaceVal interface{}
func (_e *DatastoreInterface_Expecter) Get(context1 any, key any, ifaceVal any) *DatastoreInterface_Get_Call {
	return &DatastoreInterface_Get_Call{Call: _e.mock.On("Get", context1, key, ifaceVal)}
}

func (_c *DatastoreInterface_Get_Call) Run(run func(context1 context.Context, key *datastore.Key, ifaceVal interface{})) *DatastoreInterface_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *datastore.Key
		if args[1] != nil {
			arg1 = args[1].(*datastore.Key)
		}
		var arg2 interface{}
		if args[2] != nil {
			arg2 = args[2].(interface{})
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *DatastoreInterface_Get_Call) Return(err error) *DatastoreInterface_Get_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *DatastoreInterface_Get_Call) RunAndReturn(run func(context1 context.Context, key *datastore.Key, ifaceVal interface{}) error) *DatastoreInterface_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function for the type DatastoreInterface
func (_mock *DatastoreInterface) GetAll(context1 context.Context, query *datastore.Query, ifaceVal interface{}) ([]*datastore.Key, error) {
	ret := _mock.Called(context1, query, ifaceVal)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []*datastore.Key
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *datastore.Query, interface{}) ([]*datastore.Key, error)); ok {
		return returnFunc(context1, query, ifaceVal)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *datastore.Query, interface{}) []*datastore.Key); ok {
		r0 = returnFunc(context1, query, ifaceVal)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*datastore.Key)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *datastore.Query, interface{}) error); ok {
		r1 = returnFunc(context1, query, ifaceVal)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DatastoreInterface_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type DatastoreInterface_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - context1 context.Context
//   - query *datastore.Query
//   - ifaceVal interface{}
func (_e *DatastoreInterface_Expecter) GetAll(context1 any, query any, ifaceVal any) *DatastoreInterface_GetAll_Call {
	return &DatastoreInterface_GetAll_Call{Call: _e.mock.On("GetAll", context1, query, ifaceVal)}
}

func (_c *DatastoreInterface_GetAll_Call) Run(run func(context1 context.Context, query *datastore.Query, ifaceVal interface{})) *DatastoreInterface_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *datastore.Query
		if args[1] != nil {
			arg1 = args[1].(*datastore.Query)
		}
		var arg2 interface{}
		if args[2] != nil {
			arg2 = args[2].(interface{})
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *DatastoreInterface_GetAll_Call) Return(keys []*datastore.Key, err error) *DatastoreInterface_GetAll_Call {
	_c.Call.Return(keys, err)
	return _c
}

func (_c *DatastoreInterface_GetAll_Call) RunAndReturn(run func(context1 context.Context, query *datastore.Query, ifaceVal interface{}) ([]*datastore.Key, error)) *DatastoreInterface_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// Mutate provides a mock function for the type DatastoreInterface
func (_mock *DatastoreInterface) Mutate(context1 context.Context, mutations ...*datastore.Mutation) ([]*datastore.Key, error) {
	// *datastore.Mutation
	_va := make([]any, len(mutations))
	for _i := range mutations {
		_va[_i] = mutations[_i]
	}
	var _ca []any
	_ca = append(_ca, context1)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Mutate")
	}

	var r0 []*datastore.Key
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...*datastore.Mutation) ([]*datastore.Key, error)); ok {
		return returnFunc(context1, mutations...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...*datastore.Mutation) []*datastore.Key); ok {
		r0 = returnFunc(context1, mutations...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*datastore.Key)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...*datastore.Mutation) error); ok {
		r1 = returnFunc(context1, mutations...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DatastoreInterface_Mutate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Mutate'
type DatastoreInterface_Mutate_Call struct {
	*mock.Call
}

// Mutate is a helper method to define mock.On call
//   - context1 context.Context
//   - mutations ...*datastore.Mutation
func (_e *DatastoreInterface_Expecter) Mutate(context1 any, mutations ...any) *DatastoreInterface_Mutate_Call {
	return &DatastoreInterface_Mutate_Call{Call: _e.mock.On("Mutate",
		append([]any{context1}, mutations...)...)}
}

func (_c *DatastoreInterface_Mutate_Call) Run(run func(context1 context.Context, mutations ...*datastore.Mutation)) *DatastoreInterface_Mutate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []*datastore.Mutation
		variadicArgs := make([]*datastore.Mutation, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(*datastore.Mutation)
			}
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *DatastoreInterface_Mutate_Call) Return(keys []*datastore.Key, err error) *DatastoreInterface_Mutate_Call {
	_c.Call.Return(keys, err)
	return _c
}

func (_c *DatastoreInterface_Mutate_Call) RunAndReturn(run func(context1 context.Context, mutations ...*datastore.Mutation) ([]*datastore.Key, error)) *DatastoreInterface_Mutate_Call {
	_c.Call.Return(run)
	return _c
}
