// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	uacgenerator "github.com/ONSDigital/blaise-uac-service/uacgenerator"
	mock "github.com/stretchr/testify/mock"
)

// UacGeneratorInterface is an autogenerated mock type for the UacGeneratorInterface type
type UacGeneratorInterface struct {
	mock.Mock
}

// AdminDelete provides a mock function with given fields: _a0
func (_m *UacGeneratorInterface) AdminDelete(_a0 string) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for AdminDelete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DisableUac provides a mock function with given fields: _a0
func (_m *UacGeneratorInterface) DisableUac(_a0 string) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for DisableUac")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EnableUac provides a mock function with given fields: _a0
func (_m *UacGeneratorInterface) EnableUac(_a0 string) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for EnableUac")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Generate provides a mock function with given fields: _a0, _a1
func (_m *UacGeneratorInterface) Generate(_a0 string, _a1 []string) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, []string) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllUacs provides a mock function with given fields: _a0
func (_m *UacGeneratorInterface) GetAllUacs(_a0 string) (uacgenerator.Uacs, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetAllUacs")
	}

	var r0 uacgenerator.Uacs
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (uacgenerator.Uacs, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(string) uacgenerator.Uacs); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uacgenerator.Uacs)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllUacsByCaseID provides a mock function with given fields: _a0
func (_m *UacGeneratorInterface) GetAllUacsByCaseID(_a0 string) (uacgenerator.Uacs, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetAllUacsByCaseID")
	}

	var r0 uacgenerator.Uacs
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (uacgenerator.Uacs, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(string) uacgenerator.Uacs); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uacgenerator.Uacs)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllUacsDisabled provides a mock function with given fields: _a0
func (_m *UacGeneratorInterface) GetAllUacsDisabled(_a0 string) (uacgenerator.Uacs, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetAllUacsDisabled")
	}

	var r0 uacgenerator.Uacs
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (uacgenerator.Uacs, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(string) uacgenerator.Uacs); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uacgenerator.Uacs)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetInstruments provides a mock function with no fields
func (_m *UacGeneratorInterface) GetInstruments() ([]string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetInstruments")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUacCount provides a mock function with given fields: _a0
func (_m *UacGeneratorInterface) GetUacCount(_a0 string) (int, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetUacCount")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (int, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(string) int); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUacInfo provides a mock function with given fields: _a0
func (_m *UacGeneratorInterface) GetUacInfo(_a0 string) (*uacgenerator.UacInfo, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetUacInfo")
	}

	var r0 *uacgenerator.UacInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*uacgenerator.UacInfo, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(string) *uacgenerator.UacInfo); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*uacgenerator.UacInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ImportUacs provides a mock function with given fields: _a0
func (_m *UacGeneratorInterface) ImportUacs(_a0 []string) (int, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for ImportUacs")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func([]string) (int, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func([]string) int); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func([]string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUacGeneratorInterface creates a new instance of UacGeneratorInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUacGeneratorInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *UacGeneratorInterface {
	mock := &UacGeneratorInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
