// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/ONSDigital/blaise-uac-service/uacgenerator"
	mock "github.com/stretchr/testify/mock"
)

// NewUACServiceInterface creates a new instance of UACServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUACServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *UACServiceInterface {
	mock := &UACServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UACServiceInterface is an autogenerated mock type for the UACServiceInterface type
type UACServiceInterface struct {
	mock.Mock
}

type UACServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *UACServiceInterface) EXPECT() *UACServiceInterface_Expecter {
	return &UACServiceInterface_Expecter{mock: &_m.Mock}
}

// AdminDelete provides a mock function for the type UACServiceInterface
func (_mock *UACServiceInterface) AdminDelete(context1 context.Context, s string) error {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for AdminDelete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(context1, s)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// UACServiceInterface_AdminDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AdminDelete'
type UACServiceInterface_AdminDelete_Call struct {
	*mock.Call
}

// AdminDelete is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *UACServiceInterface_Expecter) AdminDelete(context1 any, s any) *UACServiceInterface_AdminDelete_Call {
	return &UACServiceInterface_AdminDelete_Call{Call: _e.mock.On("AdminDelete", context1, s)}
}

func (_c *UACServiceInterface_AdminDelete_Call) Run(run func(context1 context.Context, s string)) *UACServiceInterface_AdminDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UACServiceInterface_AdminDelete_Call) Return(err error) *UACServiceInterface_AdminDelete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *UACServiceInterface_AdminDelete_Call) RunAndReturn(run func(context1 context.Context, s string) error) *UACServiceInterface_AdminDelete_Call {
	_c.Call.Return(run)
	return _c
}

// DisableUAC provides a mock function for the type UACServiceInterface
func (_mock *UACServiceInterface) DisableUAC(context1 context.Context, s string) error {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for DisableUAC")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(context1, s)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// UACServiceInterface_DisableUAC_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DisableUAC'
type UACServiceInterface_DisableUAC_Call struct {
	*mock.Call
}

// DisableUAC is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *UACServiceInterface_Expecter) DisableUAC(context1 any, s any) *UACServiceInterface_DisableUAC_Call {
	return &UACServiceInterface_DisableUAC_Call{Call: _e.mock.On("DisableUAC", context1, s)}
}

func (_c *UACServiceInterface_DisableUAC_Call) Run(run func(context1 context.Context, s string)) *UACServiceInterface_DisableUAC_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UACServiceInterface_DisableUAC_Call) Return(err error) *UACServiceInterface_DisableUAC_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *UACServiceInterface_DisableUAC_Call) RunAndReturn(run func(context1 context.Context, s string) error) *UACServiceInterface_DisableUAC_Call {
	_c.Call.Return(run)
	return _c
}

// EnableUAC provides a mock function for the type UACServiceInterface
func (_mock *UACServiceInterface) EnableUAC(context1 context.Context, s string) error {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for EnableUAC")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(context1, s)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// UACServiceInterface_EnableUAC_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnableUAC'
type UACServiceInterface_EnableUAC_Call struct {
	*mock.Call
}

// EnableUAC is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *UACServiceInterface_Expecter) EnableUAC(context1 any, s any) *UACServiceInterface_EnableUAC_Call {
	return &UACServiceInterface_EnableUAC_Call{Call: _e.mock.On("EnableUAC", context1, s)}
}

func (_c *UACServiceInterface_EnableUAC_Call) Run(run func(context1 context.Context, s string)) *UACServiceInterface_EnableUAC_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UACServiceInterface_EnableUAC_Call) Return(err error) *UACServiceInterface_EnableUAC_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *UACServiceInterface_EnableUAC_Call) RunAndReturn(run func(context1 context.Context, s string) error) *UACServiceInterface_EnableUAC_Call {
	_c.Call.Return(run)
	return _c
}

// Generate provides a mock function for the type UACServiceInterface
func (_mock *UACServiceInterface) Generate(context1 context.Context, s string, strings []string) error {
	ret := _mock.Called(context1, s, strings)

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []string) error); ok {
		r0 = returnFunc(context1, s, strings)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// UACServiceInterface_Generate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Generate'
type UACServiceInterface_Generate_Call struct {
	*mock.Call
}

// Generate is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - strings []string
func (_e *UACServiceInterface_Expecter) Generate(context1 any, s any, strings any) *UACServiceInterface_Generate_Call {
	return &UACServiceInterface_Generate_Call{Call: _e.mock.On("Generate", context1, s, strings)}
}

func (_c *UACServiceInterface_Generate_Call) Run(run func(context1 context.Context, s string, strings []string)) *UACServiceInterface_Generate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *UACServiceInterface_Generate_Call) Return(err error) *UACServiceInterface_Generate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *UACServiceInterface_Generate_Call) RunAndReturn(run func(context1 context.Context, s string, strings []string) error) *UACServiceInterface_Generate_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllUACs provides a mock function for the type UACServiceInterface
func (_mock *UACServiceInterface) GetAllUACs(context1 context.Context, s string) (uacgenerator.UACs, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for GetAllUACs")
	}

	var r0 uacgenerator.UACs
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (uacgenerator.UACs, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) uacgenerator.UACs); ok {
		r0 = returnFunc(context1, s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uacgenerator.UACs)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UACServiceInterface_GetAllUACs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllUACs'
type UACServiceInterface_GetAllUACs_Call struct {
	*mock.Call
}

// GetAllUACs is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *UACServiceInterface_Expecter) GetAllUACs(context1 any, s any) *UACServiceInterface_GetAllUACs_Call {
	return &UACServiceInterface_GetAllUACs_Call{Call: _e.mock.On("GetAllUACs", context1, s)}
}

func (_c *UACServiceInterface_GetAllUACs_Call) Run(run func(context1 context.Context, s string)) *UACServiceInterface_GetAllUACs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UACServiceInterface_GetAllUACs_Call) Return(uacs uacgenerator.UACs, err error) *UACServiceInterface_GetAllUACs_Call {
	_c.Call.Return(uacs, err)
	return _c
}

func (_c *UACServiceInterface_GetAllUACs_Call) RunAndReturn(run func(context1 context.Context, s string) (uacgenerator.UACs, error)) *UACServiceInterface_GetAllUACs_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllUACsByCaseID provides a mock function for the type UACServiceInterface
func (_mock *UACServiceInterface) GetAllUACsByCaseID(context1 context.Context, s string) (uacgenerator.UACs, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for GetAllUACsByCaseID")
	}

	var r0 uacgenerator.UACs
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (uacgenerator.UACs, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) uacgenerator.UACs); ok {
		r0 = returnFunc(context1, s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uacgenerator.UACs)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UACServiceInterface_GetAllUACsByCaseID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllUACsByCaseID'
type UACServiceInterface_GetAllUACsByCaseID_Call struct {
	*mock.Call
}

// GetAllUACsByCaseID is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *UACServiceInterface_Expecter) GetAllUACsByCaseID(context1 any, s any) *UACServiceInterface_GetAllUACsByCaseID_Call {
	return &UACServiceInterface_GetAllUACsByCaseID_Call{Call: _e.mock.On("GetAllUACsByCaseID", context1, s)}
}

func (_c *UACServiceInterface_GetAllUACsByCaseID_Call) Run(run func(context1 context.Context, s string)) *UACServiceInterface_GetAllUACsByCaseID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UACServiceInterface_GetAllUACsByCaseID_Call) Return(uacs uacgenerator.UACs, err error) *UACServiceInterface_GetAllUACsByCaseID_Call {
	_c.Call.Return(uacs, err)
	return _c
}

func (_c *UACServiceInterface_GetAllUACsByCaseID_Call) RunAndReturn(run func(context1 context.Context, s string) (uacgenerator.UACs, error)) *UACServiceInterface_GetAllUACsByCaseID_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllDisabledUACs provides a mock function for the type UACServiceInterface
func (_mock *UACServiceInterface) GetAllDisabledUACs(context1 context.Context, s string) (uacgenerator.UACs, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for GetAllDisabledUACs")
	}

	var r0 uacgenerator.UACs
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (uacgenerator.UACs, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) uacgenerator.UACs); ok {
		r0 = returnFunc(context1, s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uacgenerator.UACs)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UACServiceInterface_GetAllDisabledUACs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllDisabledUACs'
type UACServiceInterface_GetAllDisabledUACs_Call struct {
	*mock.Call
}

// GetAllDisabledUACs is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *UACServiceInterface_Expecter) GetAllDisabledUACs(context1 any, s any) *UACServiceInterface_GetAllDisabledUACs_Call {
	return &UACServiceInterface_GetAllDisabledUACs_Call{Call: _e.mock.On("GetAllDisabledUACs", context1, s)}
}

func (_c *UACServiceInterface_GetAllDisabledUACs_Call) Run(run func(context1 context.Context, s string)) *UACServiceInterface_GetAllDisabledUACs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UACServiceInterface_GetAllDisabledUACs_Call) Return(uacs uacgenerator.UACs, err error) *UACServiceInterface_GetAllDisabledUACs_Call {
	_c.Call.Return(uacs, err)
	return _c
}

func (_c *UACServiceInterface_GetAllDisabledUACs_Call) RunAndReturn(run func(context1 context.Context, s string) (uacgenerator.UACs, error)) *UACServiceInterface_GetAllDisabledUACs_Call {
	_c.Call.Return(run)
	return _c
}

// GetInstruments provides a mock function for the type UACServiceInterface
func (_mock *UACServiceInterface) GetInstruments(context1 context.Context) ([]string, error) {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for GetInstruments")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]string, error)); ok {
		return returnFunc(context1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = returnFunc(context1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(context1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UACServiceInterface_GetInstruments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInstruments'
type UACServiceInterface_GetInstruments_Call struct {
	*mock.Call
}

// GetInstruments is a helper method to define mock.On call
//   - context1 context.Context
func (_e *UACServiceInterface_Expecter) GetInstruments(context1 any) *UACServiceInterface_GetInstruments_Call {
	return &UACServiceInterface_GetInstruments_Call{Call: _e.mock.On("GetInstruments", context1)}
}

func (_c *UACServiceInterface_GetInstruments_Call) Run(run func(context1 context.Context)) *UACServiceInterface_GetInstruments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *UACServiceInterface_GetInstruments_Call) Return(strings []string, err error) *UACServiceInterface_GetInstruments_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *UACServiceInterface_GetInstruments_Call) RunAndReturn(run func(context1 context.Context) ([]string, error)) *UACServiceInterface_GetInstruments_Call {
	_c.Call.Return(run)
	return _c
}

// GetUACCount provides a mock function for the type UACServiceInterface
func (_mock *UACServiceInterface) GetUACCount(context1 context.Context, s string) (int, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for GetUACCount")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (int, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) int); ok {
		r0 = returnFunc(context1, s)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UACServiceInterface_GetUACCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUACCount'
type UACServiceInterface_GetUACCount_Call struct {
	*mock.Call
}

// GetUACCount is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *UACServiceInterface_Expecter) GetUACCount(context1 any, s any) *UACServiceInterface_GetUACCount_Call {
	return &UACServiceInterface_GetUACCount_Call{Call: _e.mock.On("GetUACCount", context1, s)}
}

func (_c *UACServiceInterface_GetUACCount_Call) Run(run func(context1 context.Context, s string)) *UACServiceInterface_GetUACCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UACServiceInterface_GetUACCount_Call) Return(n int, err error) *UACServiceInterface_GetUACCount_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *UACServiceInterface_GetUACCount_Call) RunAndReturn(run func(context1 context.Context, s string) (int, error)) *UACServiceInterface_GetUACCount_Call {
	_c.Call.Return(run)
	return _c
}

// GetUACInfo provides a mock function for the type UACServiceInterface
func (_mock *UACServiceInterface) GetUACInfo(context1 context.Context, s string) (*uacgenerator.UACInfo, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for GetUACInfo")
	}

	var r0 *uacgenerator.UACInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*uacgenerator.UACInfo, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *uacgenerator.UACInfo); ok {
		r0 = returnFunc(context1, s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*uacgenerator.UACInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UACServiceInterface_GetUACInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUACInfo'
type UACServiceInterface_GetUACInfo_Call struct {
	*mock.Call
}

// GetUACInfo is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *UACServiceInterface_Expecter) GetUACInfo(context1 any, s any) *UACServiceInterface_GetUACInfo_Call {
	return &UACServiceInterface_GetUACInfo_Call{Call: _e.mock.On("GetUACInfo", context1, s)}
}

func (_c *UACServiceInterface_GetUACInfo_Call) Run(run func(context1 context.Context, s string)) *UACServiceInterface_GetUACInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UACServiceInterface_GetUACInfo_Call) Return(uacInfo *uacgenerator.UACInfo, err error) *UACServiceInterface_GetUACInfo_Call {
	_c.Call.Return(uacInfo, err)
	return _c
}

func (_c *UACServiceInterface_GetUACInfo_Call) RunAndReturn(run func(context1 context.Context, s string) (*uacgenerator.UACInfo, error)) *UACServiceInterface_GetUACInfo_Call {
	_c.Call.Return(run)
	return _c
}

// ImportUACs provides a mock function for the type UACServiceInterface
func (_mock *UACServiceInterface) ImportUACs(context1 context.Context, strings []string) (int, error) {
	ret := _mock.Called(context1, strings)

	if len(ret) == 0 {
		panic("no return value specified for ImportUACs")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) (int, error)); ok {
		return returnFunc(context1, strings)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) int); ok {
		r0 = returnFunc(context1, strings)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = returnFunc(context1, strings)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UACServiceInterface_ImportUACs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ImportUACs'
type UACServiceInterface_ImportUACs_Call struct {
	*mock.Call
}

// ImportUACs is a helper method to define mock.On call
//   - context1 context.Context
//   - strings []string
func (_e *UACServiceInterface_Expecter) ImportUACs(context1 any, strings any) *UACServiceInterface_ImportUACs_Call {
	return &UACServiceInterface_ImportUACs_Call{Call: _e.mock.On("ImportUACs", context1, strings)}
}

func (_c *UACServiceInterface_ImportUACs_Call) Run(run func(context1 context.Context, strings []string)) *UACServiceInterface_ImportUACs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UACServiceInterface_ImportUACs_Call) Return(n int, err error) *UACServiceInterface_ImportUACs_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *UACServiceInterface_ImportUACs_Call) RunAndReturn(run func(context1 context.Context, strings []string) (int, error)) *UACServiceInterface_ImportUACs_Call {
	_c.Call.Return(run)
	return _c
}
