name: Test and coverage
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v2
        with:
          go-version: '1.22'
      - name: Install dependencies
        run: go mod download
      - name: Run tests
        run: go test -v -coverprofile=coverage.out ./...
      - name: Upload coverage to Codecov
        run: bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }} -B ${{ github.ref_name }} -P ${{ github.event.pull_request.head.ref }}
        env:
          token: ${{ secrets.CODECOV_TOKEN }}